### Site Settings ###
source: ../
baseurl: /
repository: mareksagan
title: Java / DevOps Expert
company: MARIS - Java / DevOps Expert - 8 years of hands on web development and DevOps
description: MARIS - Java / DevOps Expert - 8 years of hands on web development and DevOps


### Navbar Settings ###
nav_exclude:
  - docs/pages/tags.html
  - docs/pages/404.html
  - docs/pages/index.md
  - docs/pages/documentation/**


### SEO ###
tagline:
logo: https://avatars0.githubusercontent.com/u/17403762
image: https://avatars0.githubusercontent.com/u/17403762
lang: en_US
social:
  name: Marek Sagan
  links:
    - https://www.linkedin.com/in/mareksagan
    - https://stackoverflow.com/users/6444452/marek-sagan
    - https://github.com/mareksagan/
google_site_verification: 5xKbeRW3pODPz9_ZEcb1koZii9FckbF_qx7m-sLuiOU

### Author Info ###
author:
  name: Marek Sagan
  avatar: https://avatars0.githubusercontent.com/u/17403762
  email: marek.sagan@protonmail.com
  github: mareksagan
  linkedin: marek-sagan
  stackoverflow: 6444452
  phone: 0048737878782
  resume: https://github.com/mareksagan/Resume/raw/de/Marek_Sagan_JavaDevOpsExpert


### Posts ###
permalink: /blog/:title
disqus: short-name-disqus


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:
    output: true


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "elements"
    values:
      layout: "element"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

plugins:
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji


exclude:
  - test/
  - docs/Gemfile
  - docs/Gemfile.lock
  - docs/_site/
  - docs/.sass-cache/