### Site Settings ###
source              : ../
baseurl             : /
title               : "Marek Sagan"
description         : "Java / Angular Developer"


### Navbar Settings ###
nav_exclude:
  - docs/pages/tags.html
  - docs/pages/404.html
  - docs/pages/index.md
  - docs/pages/documentation/**


### Author Info ###
author:
  name: Marek Sagan
  avatar: https://avatars0.githubusercontent.com/u/17403762
  email: marek.sagan@protonmail.com
  github: mareksagan
  linkedin: marek-sagan
  stackoverflow: "6444452"


### Posts ###
permalink: /blog/:title
disqus: short-name-disqus


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:
    output: true


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "elements"
    values:
      layout: "element"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

plugins:
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji


exclude:
  - test/
  - docs/Gemfile
  - docs/Gemfile.lock
  - docs/_site/
  - docs/.sass-cache/